"""
generate_seed_sql.py
=====================
Generates seed_hotspot_demo.sql from the exact same row-building logic as
seed_hotspot_demo.py, so the two never drift apart. Produces a plain SQL
file the user can review/edit by hand and run themselves (psql, Neon's SQL
editor, etc.) against whichever database they choose — this script never
touches a database connection itself.

Usage:
    cd smart_city_citizen_reporting_app/ai_backend
    python ../../decision_support_system_web/generate_seed_sql.py
"""

import random
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Deterministic output — same SQL every time this is regenerated, so it's
# reviewable/diffable instead of silently changing on every run.
random.seed(42)

import seed_hotspot_demo as seed  # noqa: E402

OUTPUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "seed_hotspot_demo.sql")

COLUMNS = [
    "title", "description", "predictedCategory", "imageValidation", "confidence",
    "image", "longitude", "latitude", "status", "location", "address",
    "timestamp", "assigned_department", "authority_notes", "forwarded_at",
    "reviewed_at", "assigned_worker", "in_process_at", "in_maintenance_at",
    "resolved_at", "worker_completed", "upvotes", "categories",
]

ROW_KEY_MAP = {
    "predictedCategory": "ai_prediction",
    "imageValidation": "image_validation",
    "image": "image_path",
}


def sql_str(value):
    """Single-quoted, escaped SQL string literal, or NULL."""
    if value is None:
        return "NULL"
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def sql_ts(value):
    """Timestamp literal, or NULL. `value` is either a datetime or an ISO string."""
    if value is None:
        return "NULL"
    iso = value.isoformat() if hasattr(value, "isoformat") else str(value)
    return f"'{iso}'::timestamptz"


def sql_num(value):
    return "NULL" if value is None else str(value)


def format_row(row):
    parts = []
    for col in COLUMNS:
        key = ROW_KEY_MAP.get(col, col)
        val = row[key]
        if col in ("longitude", "latitude", "worker_completed", "upvotes"):
            parts.append(sql_num(val))
        elif col in ("timestamp", "forwarded_at", "reviewed_at", "in_process_at", "in_maintenance_at", "resolved_at"):
            parts.append(sql_ts(val))
        else:
            parts.append(sql_str(val))
    return "  (" + ", ".join(parts) + ")"


def main():
    rows = []

    # ── General baseline (same as seed_hotspot_demo.main) ──
    for _ in range(62):
        lat, lng, address = random.choice(seed.MELAKA_LOCATIONS)
        lat += random.uniform(-0.0015, 0.0015)
        lng += random.uniform(-0.0015, 0.0015)
        category = random.choice(seed.CATEGORIES)
        status = seed.random_status()
        timestamp = seed.random_timestamp_within_days(60)
        rows.append(seed.build_row(category=category, lat=lat, lng=lng, address=address,
                                    timestamp=timestamp, status=status))

    # ── Deliberate Hotspots (recurring-failure) clusters ──
    rows += seed.hotspot_cluster_rows(
        "Road Damage", "Kampung Morten, Melaka",
        (2.19680, 102.23920), (2.19750, 102.23850),
    )
    rows += seed.hotspot_cluster_rows(
        "Drainage", "Jalan Taman Melaka Raya, Melaka",
        (2.18780, 102.25280), (2.18850, 102.25350),
    )
    rows += seed.hotspot_cluster_rows(
        "Street Lighting", "Jalan Ayer Keroh, Melaka",
        (2.26480, 102.29200), (2.26550, 102.29270),
    )

    # ── Deliberate Systemic (cross-category) clusters ──
    rows += seed.systemic_cluster_rows(
        "Road Damage", "Drainage", "Jalan Bukit Baru, Melaka", (2.20320, 102.25870), 40,
    )
    rows += seed.systemic_cluster_rows(
        "Waste", "Drainage", "Taman Krubong Jaya, Melaka", (2.24780, 102.28850), 35,
    )
    rows += seed.systemic_cluster_rows(
        "Street Lighting", "Vandalism", "Taman Cheng Baru, Melaka", (2.22480, 102.21850), 30,
    )

    lines = [
        "-- seed_hotspot_demo.sql",
        "-- Generated by generate_seed_sql.py from the same row-building logic as",
        "-- seed_hotspot_demo.py. Review/edit freely before running.",
        "--",
        "-- WARNING: this deletes every existing report before inserting the new set.",
        "-- Run it against whichever database you intend to replace.",
        "",
        "BEGIN;",
        "",
        'DELETE FROM "report_upvotes";',
        'DELETE FROM "Issue";',
        'DELETE FROM "AuthorityAction";',
        'DELETE FROM "Complaint";',
        "",
        "WITH citizen AS (",
        '  SELECT "userID" FROM "User" LIMIT 1',
        ")",
        'INSERT INTO "Complaint" (',
        '    "userID", "title", "description", "predictedCategory",',
        '    "imageValidation", "confidence", "image",',
        '    "longitude", "latitude", "status", "location", "address",',
        '    "timestamp", "assigned_department", "authority_notes",',
        '    "forwarded_at", "reviewed_at", "assigned_worker",',
        '    "in_process_at", "in_maintenance_at", "resolved_at",',
        '    "worker_completed", "upvotes", "categories"',
        ")",
        'SELECT citizen."userID", v.*',
        "FROM citizen, (VALUES",
    ]

    formatted_rows = [format_row(r) for r in rows]
    lines.append(",\n".join(formatted_rows))

    lines += [
        ") AS v(",
        "    title, description, \"predictedCategory\", \"imageValidation\", confidence,",
        "    image, longitude, latitude, status, location, address,",
        '    "timestamp", assigned_department, authority_notes, forwarded_at,',
        "    reviewed_at, assigned_worker, in_process_at, in_maintenance_at,",
        "    resolved_at, worker_completed, upvotes, categories",
        ");",
        "",
        "COMMIT;",
        "",
        "-- Verify:",
        '-- SELECT status, COUNT(*) FROM "Complaint" GROUP BY status ORDER BY COUNT(*) DESC;',
        f"-- Expect {len(rows)} total rows ({62} general + {len(rows) - 62} engineered for",
        "-- the Recurring Failures / Systemic clusters on Predictive Hotspots).",
    ]

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {len(rows)} rows to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
